# -------------------------------------------------------------------
# execute_code.py
# Execute LLM-generated Python code and extract final FOL output.
#
# The generated code is expected to follow the CODE4LOGIC protocol:
#   - It defines intermediate variables formula_1, formula_2, ...
#   - Ends with: formula = End(<var>)
#
# This module:
#   1. Imports all basis FOL functions
#   2. Executes the code in a controlled local environment
#   3. Extracts the `formula` object
#   4. Returns its FOL string using __str__()
# -------------------------------------------------------------------

import traceback

from basis_functions.fol_functions import (
    Term, Constant, Variable, Function, Predicate,
    Negation, Conjunction, Disjunction, Implication,
    Equivalence, Nonequivalence,
    ExistentialQuantification, UniversalQuantification,
    Equal, NonEqual, GreaterThan, GreaterEqual, 
    LessThan, LessEqual, End
)


# -------------------------------------------------------------------
# SAFE EXECUTION ENVIRONMENT
# -------------------------------------------------------------------

def _get_execution_env():
    """
    Build a restricted namespace containing only
    the allowed FOL basis functions.
    This prevents the executed code from accessing Python internals.
    """

    allowed = {
        "Term": Term,
        "Constant": Constant,
        "Variable": Variable,
        "Function": Function,
        "Predicate": Predicate,

        "Negation": Negation,
        "Conjunction": Conjunction,
        "Disjunction": Disjunction,
        "Implication": Implication,
        "Equivalence": Equivalence,
        "Nonequivalence": Nonequivalence,

        "ExistentialQuantification": ExistentialQuantification,
        "UniversalQuantification": UniversalQuantification,

        "Equal": Equal,
        "NonEqual": NonEqual,
        "GreaterThan": GreaterThan,
        "LessThan": LessThan,
        "GreaterEqual": GreaterEqual,
        "LessEqual": LessEqual,

        "End": End,
    }

    return allowed

# -------------------------------------------------------------------
# Clean Code Block FUNCTION
# -------------------------------------------------------------------

def clean_code_block(code_string: str) -> str:
    """
    Remove markdown code fences such as ```python ... ``` or ``` ... ```.
    """
    lines = code_string.strip().splitlines()

    # If starts with ``` or ```python
    if lines and lines[0].strip().startswith("```"):
        lines = lines[1:]  # remove first line

    # If ends with ```
    if lines and lines[-1].strip().startswith("```"):
        lines = lines[:-1]

    return "\n".join(lines)


# -------------------------------------------------------------------
# MAIN EXECUTION FUNCTION
# -------------------------------------------------------------------

def execute_generated_code(code_string: str) -> str:
    """
    Execute the code produced by the LLM.

    Args:
        code_string: The Python code generated by the model.

    Returns:
        A string containing the final FOL formula.
    """

    # The execution namespace only contains allowed functions
    safe_env = _get_execution_env()

    try:
        # Execute the model's generated code
        cleaned_code = clean_code_block(code_string)
        exec(cleaned_code, safe_env)


        # The model must define "formula" at the end
        if "formula" not in safe_env:
            raise ValueError(
                "The executed code did not produce a variable named 'formula'."
            )

        formula_obj = safe_env["formula"]

        # Convert the object -> FOL string
        return str(formula_obj)

    except Exception as e:
        print("\n[ERROR] Failed to execute generated code.")
        print("Exception:", str(e))
        print("\n--- TRACEBACK ---")
        traceback.print_exc()
        print("-----------------\n")

        return None


# -------------------------------------------------------------------
# Manual Test
# -------------------------------------------------------------------

if __name__ == "__main__":
    test_code = """
formula_1 = Variable('x')
formula_2 = Predicate('Cat', [formula_1])
formula = End(formula_2)
"""

    print("Executing test code:\n", test_code)
    output = execute_generated_code(test_code)
    print("Output FOL:", output)
